version: "2.1"
services:

  mssql:
    build:
      context: mssql/
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: "Denmark2018"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
       sandbox-vn: 
        ipv4_address: 192.168.1.1
  api:
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    networks:
       sandbox-vn: 
        ipv4_address: 192.168.1.2

  web:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "8020:80"
    networks:
       sandbox-vn: 
        ipv4_address: 192.168.1.3    

  specflow:
    build:
      context: specflow/
      dockerfile: Dockerfile

    networks:
       sandbox-vn: 
        ipv4_address: 192.168.1.4

networks:
  sandbox-vn:
    external: true