CREATE TABLE [dbo].[Table2](
	[Id] [int] NOT NULL,
	[DateInsertedUtc] [datetime2](7) NOT NULL,
	[LastUpdatedUtc] [datetime2](7) NOT NULL,
	[LastUserId] [nvarchar](32) NULL,
 CONSTRAINT [PK_Table2] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
