FROM microsoft/mssql-server-windows-developer

#copy the migration

#run migration steps from external volume
CMD [ "poweshell", "Run.ps1","serverInstance",".\\","database","ServiceHealth" ]

#inject initial data

#show server details

 